version: "3.8"

services:
  pulsar:
    image: apachepulsar/pulsar:2.10.0
    ports:
      - 6650:6650
      - 8080:8080
    command: sh -c "bin/apply-config-from-env.py conf/standalone.conf && bin/pulsar standalone"
    container_name: pulsar
  pulsar-node:
    build:
      context: ./
      dockerfile: Dockerfile
    image: pulsar-node:test
    container_name: pulsar-node
  pulsar-node-cons:
    image: pulsar-node-cons:test
    container_name: pulsar-node-cons
