version: "3.8"

services:
  pulsar:
    image: apachepulsar/pulsar:2.10.0
    expose:
      - 6650
      - 8080
    command: |
      sh -c "bin/apply-config-from-env.py conf/standalone.conf && bin/pulsar standalone"
    container_name: pulsar-cont
  pulsar-node-destination:
    image: pulsar-node:destination
    container_name: pulsar-node-destination-cont
    depends_on:
      - pulsar
  pulsar-node-source:
    build:
      context: ./
      dockerfile: Dockerfile
    image: pulsar-node:source
    container_name: pulsar-node-source-cont
    depends_on:
      - pulsar-node-destination

