version: "3.8"

services:
  pulsar:
    image: apachepulsar/pulsar:2.10.0
    expose:
      - 6650
      - 8080
    command: |
      sh -c "bin/apply-config-from-env.py conf/standalone.conf && bin/pulsar standalone"
    container_name: pulsar
    networks:
      - pulsar-network
  pulsar-node-destination:
    image: pulsar-node:latest
    container_name: pulsar-node-destination
    environment:
      - TYPE=DESTINATION
    networks:
      - pulsar-network
    depends_on:
      - pulsar
  pulsar-node-source:
    image: pulsar-node:latest
    container_name: pulsar-node-source
    environment:
      - TYPE=SOURCE
    networks:
      - pulsar-network
    depends_on:
      - pulsar-node-destination

networks:
  pulsar-network:
    name: pulsar-network

