version: "3.8"

services:
  kafka-node-destination:
    image: kafka-node:latest
    container_name: kafka-node-destination
    environment:
      - TYPE=DESTINATION
    networks:
      - kafka-devenv
  kafka-node-source:
    image: kafka-node:latest
    container_name: kafka-node-source
    environment:
      - TYPE=SOURCE
    networks:
      - kafka-devenv
    depends_on:
      - kafka-node-destination

networks:
  kafka-devenv:
    name: devenv
    external: true
